version: '3'

services:
  mongodb:
    build:
      context: ./mongodb
    ports:
      - "27010:27017"
    networks:
      - app-network
   
  api-gateway:
    build:
      context: ./apigateway
    ports:
      - "5001:5001"
    networks:
      - app-network
   
  evaluation-microservice:
    build:
      context: ./evaluationmicroservice
    ports:
      - "7001:7001"
    networks:
      - app-network
  
  storage-microservice:
    build:
      context: ./storagemicroservice
    ports:
      - "6001:6001"
    networks:
      - app-network
    depends_on:
      - mongodb
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    networks:
      - app-network
   
networks:
  app-network:
    driver: bridge
