apiVersion: v1
kind: Service
metadata:
  name: storage-microservice
spec:
  type: LoadBalancer
  selector:
    app: storage-microservice
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
